config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :path_prefix => 'us'
  get "help", to: 'static_pages#help' 

  #Rails.application.routes.draw do
    #devise_for :users, controllers: {
      #sessions: 'users/sessions', 
      #registrations: 'users/registrations'    
  #}
  #end

  namespace :charts do  
    get "new-clients" 
    get "new-orders" 
    get "income-orders" 
    get "order-status"
  end

  resources :users
  resources :clients
  resources :drivers
  resources :products
  resources :orders 
  resources :trucks 
  resources :drivers_trucks 


  root 'static_pages#home'
  
  get :search, controller: :main 
  root to: "main#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Inicio")%>
<% if user_signed_in? %>  
	<div class="container">
	  <div class="jumbotron">
	    <h1>Dashboard</h1> 
	    <p>Bienvenido <%= current_user.fullName %>!, 	
	    	<% if current_user.role == "admin" %>
	   		ha ingresado como Administrador
	   	<% elsif current_user.role == "employee" %> 
	   		ha ingresado como Empleado
		<% end %>  </p>  
		<p>Gráficos</p>
		
		<h2>Registro de clientes</h2> 
		<%= line_chart charts_new_clients_path %>
			<h2>Nuevos pedidos</h2> 
			<%= line_chart charts_new_orders_path %>  

			<h2>Estado de pedidos</h2> 
			<%= pie_chart charts_order_status_path %>   

	  </div>
	</div>
<% else %>  
<% end %>