config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :path_prefix => 'us'
  get "help", to: 'static_pages#help' 

  #Rails.application.routes.draw do
    #devise_for :users, controllers: {
      #sessions: 'users/sessions', 
      #registrations: 'users/registrations'    
  #}
  #end

  namespace :charts do  
    get "new-clients" 
    get "new-orders" 
    get "income-orders" 
    get "order-status"
  end

  resources :users
  resources :clients
  resources :drivers
  resources :products
  resources :orders 
  resources :trucks 
  resources :drivers_trucks 


  root 'static_pages#home'
  
  get :search, controller: :main 
  root to: "main#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/drivers_truck.rb
class DriversTruck < ApplicationRecord
  belongs_to :driver
  belongs_to :truck 

  accepts_nested_attributes_for :driver, :truck

  #validaciones
  validates_presence_of :assignment_date
  #validates :driver_id, uniqueness: { scope: :truck_id, message: "Conductor solo puede usar un vehiculo a la vez" }
  validate :fecha_asignacion_pasado, :fecha_asignacion_futuro
  validates :assignment_date, uniqueness: { scope: [:driver_id, :truck_id] }     
  validates :truck_id, uniqueness: { scope: [:assignment_date] }     


  def fecha_asignacion_pasado 
    if !assignment_date.blank? && assignment_date < Date.today 
      errors.add(:assignment_date, "Fecha incorrecta, no se puede asignar al pasado") 
    end 
  end

  def fecha_asignacion_futuro 
    if !assignment_date.blank? && assignment_date > Date.today+30 
      errors.add(:assignment_date, "Fecha incorrecta, no se puede asignar un camion despues de 30 dias")
    end
  end  

  #def validar_asignaciones_multiples 

    #asignaciones = DriversTruck.all 
    #asignaciones.each do |asignacion| 
      #if beginning_date > asignacion.beginning_date && beginning_date < asignacion.ending_date 
        #errors.add(:beginning_date, " El vehiculo esta ocupado durante esas fechas") 
      #elsif ending_date > asignacion.beginning_date && ending_date < asignacion.ending_date 
        #errors.add(:beginning_date, " El vehiculo ya esta reservado hasta esta fecha ")
      #end 
    #end
  #end


end

app/controllers/drivers_trucks_controller.rb
class DriversTrucksController < ApplicationController

  before_action :authenticate_user! 
  load_and_authorize_resource


  def index 
    @drivers_trucks = DriversTruck.all
  end

  def new 
   
    @drivers_truck = DriversTruck.new

  end


  def create 
    
    @drivers_truck = DriversTruck.new(drivers_truck_params)


    if @drivers_truck.save 
      flash[:success] = "Asignacion al camion exitosamente creada" 
      redirect_to drivers_trucks_path 
    else 
      flash[:error] = "Asignacion erronea, intente mas tarde" 
      render :new 
    end

  end

  def edit 
    @drivers_truck = DriversTruck.find(params[:id])
  end

  def update   
    
    @drivers_truck = DriversTruck.find(params[:id])


    if @drivers_truck.update(drivers_truck_params) 
      flash[:success] = "Se ha modificado la asignación" 
      redirect_to drivers_trucks_path 
    else 
      flash[:error] = "Asignación errónea, intente más tarde" 
      render :edit 
    end
  end

  def destroy 
    
    @drivers_truck = DriversTruck.find(params[:id])
    
    if @drivers_truck.destroy 
      flash[:success] = "Se ha eliminado la asignación" 
      redirect_to drivers_trucks_path 
    else 
      flash[:error] = "Ha habido un error al intentar eliminar la asignacion, intente mas tarde" 
      redirect_to drivers_trucks_path 
    end

  end

  private 

    def drivers_truck_params 
      params.require(:drivers_truck).permit(:driver_id, :truck_id, :assignment_date)
    end

end

app/views/drivers_trucks/_formulario.html.erb
<body>
  <div class="row">
    <div class="col-md-6">
        <%= form_for [@driver,@truck,@drivers_truck] do |f| %>


          <% if @drivers_truck.errors.any? %>
            <ul class = "alert alert-warning">
              <%= pluralize(drivers_truck.errors.count, "Errores") %>
            <% @drivers_truck.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          <% end %>
          <p>
          <%= f.label :Conductor  %>
            <p>
            <%= f.collection_select :driver_id, Driver.all, :id, :fullName, type: "button", include_blank: "Seleccione conductor", class: "btn btn-default btn-sm dropdown-toggle"%>
            </p>
          </p>
          <p>
          <%= f.label :Camión %>
            <p>
            <%= f.collection_select :truck_id, Truck.all, :id, :fullModel, type: "button", include_blank: "Seleccione vehiculo", class: "btn btn-default btn-sm dropdown-toggle" %>
            </p>
          </p>

          <p>
          <%= f.label :Fecha_asignacion %>
          <p>
            <%= f.text_field :assignment_date, class: 'form-control datepicker', autocomplete: "off", placeholder: 'DD-MM-AAAA' %>

          </p>
          </p>
        

          <p>
          <%= f.submit "Aceptar", class: "btn btn-primary"%>
          </p>
        <% end %>
      </div>
  </div>
</body>

app/views/drivers_trucks/edit.html.erb
<% provide(:title, "Modificar Asignacion")%>
<% provide(:path, edit_drivers_truck_path(@drivers_truck))%>
<head>

</head>
<h1>Modificar Asignacion de conductor</h1>
<%= render 'formulario' %>

app/views/drivers_trucks/index.html.erb
<% provide(:title, "Asignaciones") %>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <div class="container">
    <h1>Asignaciones</h1>

    <div style="overflow-x:auto;">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Conductor</th> 
          <th>RUT Conductor</th>
          <th>Patente Camión</th>
          <th>Modelo</th> 
          <th>Fecha asignacion</th>
          <th>Opciones</th>


        </tr>
      </thead>
      <tbody>
        <% @drivers_trucks.each do |drivers_truck| %>
          <tr>
            <td><%= drivers_truck.driver.fullName %></td> 
            <td><%= drivers_truck.driver.rut %></td>
            <td><%= drivers_truck.truck.number_plate %></td>
            <td><%= drivers_truck.truck.name %></td>
            <td><%= drivers_truck.assignment_date %></td> 
            <td><%= link_to edit_drivers_truck_path(drivers_truck), class: "btn btn-primary" do %>
                  <i class="far fa-edit"></i> Editar
                <% end %> 
                <% if can? :destroy, drivers_truck %>

                  <%= link_to drivers_truck_path(drivers_truck),
                            method: :delete,
                            data: {confirm: '¿Estas seguro?'}, class: "btn btn-danger" do %>
                              <i class="far fa-trash-alt">  </i> Eliminar </td>

                  <% end %>
                <% end %>

          </tr>
          <% end %>
      </tbody>
    </table>
    </div>
  </div>
  </body>
</html>

app/views/drivers_trucks/new.html.erb
<% provide(:title, "Asignar conductor") %>
<h1> Asignar conductor a un camión </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'formulario',drivers_truck: @drivers_truck %>

  </div>

</div>