config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :path_prefix => 'us'
  get "help", to: 'static_pages#help' 

  #Rails.application.routes.draw do
    #devise_for :users, controllers: {
      #sessions: 'users/sessions', 
      #registrations: 'users/registrations'    
  #}
  #end

  namespace :charts do  
    get "new-clients" 
    get "new-orders" 
    get "income-orders" 
    get "order-status"
  end

  resources :users
  resources :clients
  resources :drivers
  resources :products
  resources :orders 
  resources :trucks 
  resources :drivers_trucks 


  root 'static_pages#home'
  
  get :search, controller: :main 
  root to: "main#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders, inverse_of: :product, dependent: :delete_all
  has_many :clients, through: :orders

  validates :detail, presence: { message: "no puede estar en blanco" }, length: { in: 4..20 , :message => " Se requiere mas informacion en detalles"}
  validates :price, presence: { message: "no puede estar en blanco" }, numericality: { only_integer: true , :message => "El precio no tiene formato valido"}
  validates :product_number, presence: { message: "no puede estar en blanco" }, numericality: { only_integer: true , :message => "El codigo de producto no tiene formato valido"}, length: { in: 3..3 , :message => "Tiene que ser de 3 cifras"}, uniqueness: { message: "Ya existe" }
  validates :stock, presence: { message: "no puede estar en blanco" }, numericality: { only_integer: true , :message => "El stock no tiene formato valido"}




end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user! 
  load_and_authorize_resource


  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Producto almacenado correctamente"
      redirect_to products_path
    else
      flash[:error] = "Producto no se ha almacenado correctamente"
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "Se han actualizado los datos del producto"
      redirect_to products_path
    else
      flash[:error] = "No se han podido actualizar los datos del producto"
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])

    if @product.destroy
      flash.now[:notice] = "Se ha eliminado el producto"
      redirect_to products_path
    else
      flash.now[:alert] = "Ha habido un error al intentar eliminar el producto, intente mas tarde"
      redirect_to products_path
    end
  end

  private

    def product_params
      params.require(:product).permit(:detail, :price, :product_number, :stock)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_formulario.html.erb
<body>
  <div class="row">
    <div class="col-md-6">
      <%= form_for(@product) do |f| %>

          <% if @product.errors.any? %>
            <ul class = "alert alert-warning">
              <%= pluralize(@product.errors.count, "Errores") %>
              <% @product.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          <% end %>
          <p>
          <%= f.label :Detalles %></br>
          <%= f.select :detail, options_for_select(['botella 1.5 lts', 'botella 2.0 lts', 'botella 2.5 lts', 'botella 3 lts', 'dispensador 20 lts']), class: 'form-control', include_blank: "Especificacion del producto"  %>
          </p>
          <p>
          <%= f.label :Precio %>
          <%= f.text_field :price, class: 'form-control' , placeholder: "Ingresar precio del producto" %>
          </p>
          <p>
          <%= f.label :Código_de_producto %>
          <%= f.text_field :product_number, class: 'form-control' , placeholder: "Ingresar codigo de identificacion" %>
          </p>
          <p>
          <%= f.label :Stock %>
          <%= f.text_field :stock, class: 'form-control',placeholder: "Stock" %>
          </p>
          <p>
          <%= f.submit "Aceptar", class: "btn btn-primary" %>
          </p>
        <% end %>

      </div>
  </div>
</body>

app/views/products/edit.html.erb
<% provide(:title, "Editar producto")%>
<% provide(:path, edit_product_path)%>
<head>

</head>
<h1>Editar Producto</h1>
<%= render 'formulario' %>

app/views/products/index.html.erb
<% provide(:title, "Productos") %>
<html>
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <div class="container">
    <p>
    <h1>Productos</h1>
    </p>
    <div style="overflow-x:auto;">
    <table class="table table-striped">
      <thead class="thead-dark">
        <tr>
          <th>Codigo</th>
          <th>Precio</th>
          <th>Detalles</th>
          <th>Disponibilidad</th>
          <th>Opciones</th>


        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.product_number %></td>
            <td><%= product.price %></td>
            <td><%= product.detail %></td>
            <td><%= product.stock %></td>
            <td><%= link_to edit_product_path(product), class: "btn btn-primary" do %>
                  <i class="far fa-edit"></i> Editar
                <% end %>
                <% if can? :destroy, product %>

                  <%= link_to product_path(product),
                            method: :delete,
                            data: {confirm: '¿Estas seguro?'}, class: "btn btn-danger" do %>
                              <i class="far fa-trash-alt">  </i> Eliminar </td>

                  <% end %>
                <% end %>

          </tr>
          <% end %>
      </tbody>
    </table>
    </div>
  </div>
  </body>
</html>

app/views/products/new.html.erb
<% provide(:title, "Agregar Producto") %>
<h1> Agregar un nuevo Producto </h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'formulario', product: @product %>

  </div>

</div>