config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :path_prefix => 'us'
  get "help", to: 'static_pages#help' 

  #Rails.application.routes.draw do
    #devise_for :users, controllers: {
      #sessions: 'users/sessions', 
      #registrations: 'users/registrations'    
  #}
  #end

  namespace :charts do  
    get "new-clients" 
    get "new-orders" 
    get "income-orders" 
    get "order-status"
  end

  resources :users
  resources :clients
  resources :drivers
  resources :products
  resources :orders 
  resources :trucks 
  resources :drivers_trucks 


  root 'static_pages#home'
  
  get :search, controller: :main 
  root to: "main#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "Acerca de",   '#' %></li>
      <li><%= link_to "Contacto", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 
  <input class="form-control" id="myInput" type="text" placeholder="Search..">

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse "> 
  <div class="container-fluid">
    <div class="navbar-header">
    <meta name="viewport" content="width=device-width, user-scalable=false;">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Sistema</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav"> 
        <% if user_signed_in? %> 
            <li class="active"><%= link_to root_path do %> <i class="fas fa-home"></i> <% end %> </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Clientes <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a><%= link_to "Ver clientes", clients_path%></a></li>
                <li><a><%= link_to "Agregar Cliente", new_client_url%></a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Pedidos <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a><%= link_to "Ver pedidos", orders_path%></a></li>
                <li><a><%= link_to "Agregar pedido", new_order_url%></a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Productos <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a><%= link_to "Ver productos", products_path%></a></li>
                <li><a><%= link_to "Agregar producto", new_product_url%></a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Conductores <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a><%= link_to "Ver conductores", drivers_path%></a></li>
                <li><a><%= link_to "Agregar conductores", new_driver_url%></a></li>  
                <li><a><%= link_to "Asignar conductor a camión", new_drivers_truck_url%></a></li> 
                <li><a><%= link_to "Ver asignaciones", drivers_trucks_path%></a></li> 
              </ul>
            </li> 
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Camiones <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a><%= link_to "Ver camiones", trucks_path%></a></li>
                <li><a><%= link_to "Agregar camion", new_truck_url%></a></li>
              </ul>	
            </li> 
            <% if current_user.role == "admin" %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Usuarios <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a><%= link_to "Ver usuarios", users_path%></a></li>
                </ul> 
              </li> 
            <% end %>
          </ul>  


        		

        <% else %>  
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>   
        	<li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"> <i class="fas fa-user"></i> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a><%= link_to current_user.email %></a></li>  
              <li><a><%= link_to current_user.fullName %></a></li>  
              <% if current_user.role == "admin" %>
                  <li><a>Administrador</a></li> 
                <% elsif current_user.role == "employee" %> 
                  <li><a>Empleado</a></li> 
              <% end %>
              <li><a><%= link_to "Editar Cuenta", edit_user_registration_path %></a></li>
              <li><a><%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %></a></li>
            </ul>
          </li>
        <% else %>
          <li> <%= link_to new_user_registration_path do%><i class="fas fa-user"></i> Registrarse <% end %></li> 
          <li> <%= link_to new_user_session_path do %><i class="fas fa-sign-in-alt"></i> Iniciar sesión <% end %></li>  
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_searchbyname.html.erb
  <div class="search-container">
    <form action="/action_page.php"> 
      <input class="form-control" type="text" id="myInput" onkeyup="myFunction()" placeholder="Buscar por nombre..." name="search">
    </form>
  </div>

app/views/layouts/_searchbyplate.html.erb
  <div class="search-container">
    <form action="/action_page.php"> 
      <input class="form-control" type="text" id="myInput" onkeyup="myFunction()" placeholder="Buscar por patente..." name="search">
    </form>
  </div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/nav'%>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <script src="jquery.rut.js"></script>
    <%= render 'layouts/shim' %> 
  </head>

  <body>
    <div class = "container"> 
      <% if notice %><div class = "alert alert-info"><%= notice %></div><%end%>
      <% if alert %><div class = "alert alert-warning"><%= alert %></div><%end%>
      <%= yield %>
      </div>
  </body>
</html>